name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test_ssh_connection:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}  # IP address of the server
          username: ${{ secrets.USER }}  # SSH username (root in this case)
          password: ${{ secrets.SSH_PASSWORD }}  # Replace with your SSH password
          script: | 
            echo "Testing SSH connection"
            # Add any additional commands you want to run on the server via SSH here
